baseURL: http://example.org/
languageCode: en-us
title: Abhay Vashist
theme: "PaperMod"


# languages:
#   en:
#     languageName: "English"
#     weight: 1
#     taxonomies:
#       category: categories
#       tag: tags
#       series: series
menu:
  main:
  - name: Archive
    url: archives
    weight: 5
  - name: Search
    url: search/
    weight: 10
  - name: Tags
    url: tags/
    weight: 10
params: 
  defaultTheme: auto
  homeInfoParams:
    Title: Hi there
    Content: >
      Welcome to my page, I am experienced in HTML, CSS, Java, Matlab, Python, and Solidworks. 
      I am also proficient in coding SQLite databases and create Django bases web application. 
      I also have experience working with microcontrollers as PID for a system and to filter incoming singles. 
      I have also developed a user interface for multiple application in iOS and Android using android studio and Xcode.
      

      --------

      ### Where I have worked


      #### Argo AI, Austin, Texas &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Febuary 2022 - November 2022


        - Software Developer


      #### PCS Software, Houston, Texas &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; January 2021 - December 2021


        - AI/ML developer

      #### Engineering World Health, Kigali, Rwanda &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp; January 2021 - December 2021

      ---------


      ### Where I studies


      #### Masters of Science(Non-Thesis), Texas A&M University &emsp;&emsp;&emsp; August 2019 - August 2020


        - Electrical Engineering - Information Science and Systems


      #### Bachelor of Science, Texas A&M University &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp; August 2016 - August 2019


        - Biomedical Engrineering - Bioinstrumentation & Bioimaging


      ---------



      

  socialIcons:
      - name: github
        url: "https://github.com/avashist1998"
      - name: linkedIn
        url: "https://www.linkedin.com/in/abhayvashist"

outputs:
    home:
        - HTML
        - JSON # is necessary